services:
  app:
    container_name: app
    build: ./server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - app
      - db
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    env_file:
      - ".env"
      
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
