services:
  flask:
    container_name: flask
    build: ./server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - flask-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - flask
      - db
      - admin
    networks:
      - flask-network

  admin:
    container_name: admin
    build: ./admin
    restart: always
    ports:
      - "5001:5001"
    networks:
      - flask-network


  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=db
    ports:
      - "3307:3306"
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge



